name: jax-gpu-env
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - libmamba
  # Core JAX + GPU
  - jax
  - jaxlib=*=*cuda*
  - cuda-nvcc
  # Scientific Stack (Let Conda pick the best versions for the cluster)
  - h5py
  - ipython
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tqdm
  - optax
  - pip
  - pip:
    - absl-py==2.4.0
    - aiofiles==25.1.0
    - asttokens==3.0.0
    - autograd==1.7.0
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - chex==0.1.91
    - comm==0.2.2
    - contourpy==1.2.1
    - corner==2.2.2
    - cryptography==46.0.4
    - cycler==0.12.1
    - dataclasses-json==0.6.7
    - debugpy==1.8.12
    - decorator==5.1.1
    - diffrax==0.7.0
    - dotmap==1.3.30
    - equinox==0.13.2
    - et-xmlfile==1.1.0
    - etils==1.13.0
    - evosax==0.2.0
    - executing==2.2.0
    - filelock==3.19.1
    - flax==0.12.4
    - fonttools==4.53.1
    - fsspec==2025.9.0
    - humanize==4.15.0
    - importlib_resources==6.5.2
    - ipykernel==6.29.5
    - ipyparallel==9.0.0
    - jaxtyping==0.3.2
    - jedi==0.19.2
    - Jinja2==3.1.6
    - joblib==1.4.2
    - jupyter_client==8.6.3
    - jupyter_core==5.7.2
    - kiwisolver==1.4.5
    - lineax==0.0.8
    - markdown-it-py==4.0.0
    - MarkupSafe==3.0.2
    - marshmallow==3.26.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - ml_dtypes==0.5.3
    - mpmath==1.3.0
    - msgpack==1.1.2
    - multipledispatch==1.0.0
    - mypy_extensions==1.1.0
    - nest-asyncio==1.6.0
    - networkx==3.5
    - numdifftools==0.9.41
    - numpyro==0.19.0
    - openpyxl==3.1.5
    - opt_einsum==3.4.0
    - optimistix==0.0.10
    - orbax-checkpoint==0.11.33
    - orbax-export==0.0.8
    - packaging==24.1
    - parso==0.8.4
    - patsy==1.0.1
    - pdfminer.six==20251230
    - pdfplumber==0.11.9
    - pexpect==4.9.0
    - pillow==12.0.0
    - platformdirs==4.3.6
    - prompt_toolkit==3.0.50
    - protobuf==6.33.5
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pycparser==3.0
    - Pygments==2.19.1
    - pyparsing==3.1.2
    - pypdfium2==5.3.0
    - pyreadstat==1.2.8
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - PyYAML==6.0.3
    - pyzmq==27.1.0
    - rich==14.3.3
    - sas7bdat==2.2.3
    - seaborn==0.13.2
    - setuptools==68.0.0
    - simplejson==3.20.2
    - six==1.16.0
    - stack-data==0.6.3
    - statsmodels==0.14.4
    - sympy==1.14.0
    - tensorstore==0.1.81
    - threadpoolctl==3.6.0
    - toolz==1.1.0
    - tornado==6.4.2
    - traitlets==5.14.3
    - treescope==0.1.10
    - typing-inspect==0.9.0
    - typing_extensions==4.15.0
    - tzdata==2024.1
    - uvloop==0.22.1
    - wadler_lindig==0.1.6
    - wcwidth==0.2.13
    - wheel==0.46.3
    - zipp==3.23.0